### ISSUE TITLE
[1.12.2] Locational Armor for Modded Chest/Helm Swapped

### ISSUE THREAD

**Issue by Ameranth** [ichttt/FirstAid#108]
Hello again and thank you for your work!

Unsure if this is a problem with First Aid, or how some other mods implement their armors, but I've seen that some locational armor values for modded chest and helm appear to be swapped (noticed with [Ice and Fire's](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) Deathworm and Tide armor):
![LocalArmor](https://user-images.githubusercontent.com/74480944/103387185-fbe57b80-4ac7-11eb-9411-273c37acb751.png)

Or perhaps I'm misunderstanding the system, but it seems to me that the local armor values for chest should be higher than that of the helmet--given the original values shown.

Thank you again for your time!

**Comment by ichttt** [comment]
These values are actually intended that way, since armor in minecraft is balanced around the most armor being on the chestplate (as it is the most expensive item), but the locational armor should be somewhat similar for each body region if all items are the same tier (so e.g. a diamond helmet should roughly give the same locational armor as a diamond chestplate). To accomplish that, there is a fomular that multiplies the values. So yes, this is actually correct, to balance out locational armor

**Comment by Ameranth** [comment]
I think I understand what you're saying, but shouldn't the chest higher armor, then?

**Comment by ichttt** [comment]
No, it's fine this way. Helmet is designed to have a little more than anything else most of the time to reduce the damage of headshots.

**Comment by Ameranth** [comment]
I guess, but that's not the intended design, as is evidenced by the original values being lower on the helmet than chest (as you pointed out, they are designed _this_ way) and your own system giving more armor to chest in usual circumstances--there is clearly an extenuating factor in play on some modded items.

Either way, thank you for your time and reply, I can only respect your decision on the matter, especially given that it only affects modded some items.
