### ISSUE TITLE
Totem of Undying kill you after revive you

### ISSUE THREAD

**Issue by TBiscuit1** [ichttt/FirstAid#82]
When I break a totem of undying, It got used AND I died right after because of "death.attack.magic.player" what

**Comment by ichttt** [comment]
Please try the beta build below and see if the issue still persists.
Due to missing context, I guess that you are on minecraft 1.12.2 (which this build is for)
[firstaid-1.6.14-BETA.zip](https://github.com/ichttt/FirstAid/files/4402556/firstaid-1.6.14-BETA.zip)
Simply unzip the jar file and place it in your mods folder. Don't forget to remove the old firstaid file.
If this fixes the issue, I will make this an official release soon

**Comment by D-Bigboy-302** [comment]
Hi! I'm having a similar issue as well. I'm using the 1.14 version and when I die the totem is used though it doesn't save me from death.

**Comment by ichttt** [comment]
Should be fixed by 9cb326fbabd522f0ffa768ef11c7259504a66728 for 1.12, version will be release on CF this week. 1.14 and 1.15 will receive the fix soon(tm) as well
