### ISSUE TITLE
[1.15.2] Spawn with no health?

### ISSUE THREAD

**Issue by HailTheRavenKing** [ichttt/FirstAid#86]
Whenever I start a new world, I start out with 0 hearts on all of my parts and have to kill myself before I respawn with full health

**Comment by ichttt** [comment]
It sounds like you are using an incompatible server software. Can you reproduce this with only forge and this mod on the latest version of this mod?

**Comment by ichttt** [comment]
Closing due to missing information

**Comment by TsplayerT** [comment]
I have this same problem and I believe it is because of the mod  `Spice of Life: Carrot Edition`

Minecraft version: 1.16.4
forge: 35.1.13
firstaid version: 1.9.5
solcarrot version: 1.16.3-1.9.8

[latest.log](https://github.com/ichttt/FirstAid/files/5756427/latest.log)
[debug.log](https://github.com/ichttt/FirstAid/files/5756428/debug.log)
