### ISSUE TITLE
Skeletons always headshotting in hard mode

### ISSUE THREAD

**Issue by Rafael-Leal-Prada-dos-Santos** [ichttt/FirstAid#95]
Is there any way to reduce the damage caused by skeleton headshots? Even if the user is using a diamond armor he's still getting one shot all the time by them. That makes the game impossible to play. Because if you get one shot all the time even with armor it doesn't make sense to have armor in the game.
Is there any config file that I can use to change this?

**Comment by Catlord-3** [comment]
1. I am pretty sure this is an intended feature
2. I have played on rlcraft, and while they do a lot of damage with full diamond, they still take a few hits to kill you
Maybe try setting the difficulty to normal instead of hard instead, or maybe you dont notice your head is at low hp when your healthbar is mostly full. (press h (default key) to see your different body parts health. also if you are playing with mods that reduce health maybe stop using those, and ones that increase skeleton damage.) 

Recommendations: personal preference but play with mods that add armor that is better then diamond that can be achieved within a reasonable time, like ice and fire. also reccomend scaling health as you get extra health which makes it where you die a lot less. Third maybe use a mod that removes/nerfs skeletons or makes them fight melee.

**Comment by Catlord-3** [comment]
Also, what KIND of armor are you using? if you are using anything but a helmet it will not help your head, but helmet protection is severely buffed (to about the same as chestplate). So even if you have god boots, sorry, they wont help against skeletons. (pro tip, skip out on leggings/bootsas while it may slow you down with broken legs, you will still will be alive.)

One more thing, there is a config option to make it where head health hitting 0 is not lethal, along with chest. i am not sure how these work, as i always felt that they were fine on, but the option is there

**Comment by Catlord-3** [comment]
The option is easy to find, just go to First aid->damage and it is right at the top, though you need to not be in game to use this config

**Comment by ichttt** [comment]
Skeletons always aim for head, but they don't always hit the head. That's vanilla behaviour. You can disable headshots being fatal in the config (See Damage System -> causeDeathHead)
